version: '3'
services:
        db:
                image: postgres:9.5.10
                volumes:
                        - ./scheduleAPI/tmp/db:/var/lib/postgresql/data
        api:
                build:
                  context: ./scheduleAPI
                  dockerfile: Dockerfile.prod
                command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
                volumes:
                        - ./scheduleAPI:/myapp
                # ports:
                #         - "3000:3000"
                depends_on:
                        - db
                environment:
                        RAILS_ENV: production
                        SECRET_KEY_BASE: ${SECRET_KEY_BASE}

        web_ap:
                build:
                  context: ./scheduleWEB
                  dockerfile: Dockerfile.prod
                command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3030 -b 0.0.0.0"
                volumes:
                        - ./scheduleWEB:/myapp
                # ports:
                #         - "3030:3030"
                depends_on:
                        - api
                environment:
                        RAILS_ENV: production
                        SECRET_KEY_BASE: ${SECRET_KEY_BASE}

        line_api:
                build:
                  context: ./lineAPI
                  dockerfile: Dockerfile.prod
                command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3040 -b 0.0.0.0"
                volumes:
                        - ./lineAPI:/myapp
                # ports:
                #         - "3040:3040"
                depends_on:
                        - api
                environment:
                        RAILS_ENV: production
                        SECRET_KEY_BASE: ${SECRET_KEY_BASE}

        web:
                image: nginx
                ports:
                        - "443:443"
                depends_on:
                        - line_api
                        - web_ap
                volumes:
                        - ./web/log:/var/log/nginx
                        - ./web/default.conf:/etc/nginx/conf.d/default.conf
                        - ./scheduleWEB/public:/usr/share/nginx/public
                        - /etc/letsencrypt:/etc/letsencrypt
